spring:
  security:
    user:
      name: user
      password: 1234
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: #{client-id}
#            client-secret: #{client-secret}
#            redirect-uri: "https://{baseHost}{basePort}/login/oauth2/code/{registrationId}"